project:
  type: book
  output-dir: docs
  
execute:
  freeze: auto

lang: pt 

book:
  title: "R intermediário e pesquisa reprodutível"
  site-url: "https://ipeadata-lab.github.io/curso_r_intermediario_202501"
  repo-url: "https://github.com/ipeadata-lab/curso_r_intermediario_202501"
  chapters:
    - text: "Página inicial"
      href: index.qmd  
    - href: calendario.qmd
    - href: instalacao.qmd
    - href: reprodutibilidade.qmd
    - href: relatorios.qmd
    - href: git-github.qmd    
    - href: texto-data.qmd
    - href: big-data.qmd    
    - href: programacao-funcional.qmd
    - href: dados-espaciais.qmd    

page-navigation: true

page-footer: 
  border: true
  left: "Copyright 2025, Beatriz Milz e IPEA/COCD" 
  right: 
    - icon: github
      href: https://github.com/ipeadata-lab/curso_r_intermediario_202501


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 5
    link-external-icon: false
    link-external-newwindow: true

bibliography: references.bib

editor: source
