---
title: "Calendário do curso"
---

A maioria das aulas acontecerão às segundas e quartas-feiras, exceto a aula do dia 30/01/2025, que acontecerá numa quinta-feira.

As aulas acontecerão das 09h às 12h, com intervalo de 15 minutos.

Segue o calendário do curso:

| Semana | Data | Horário | Dia da semana | Conteúdo previsto |
|--|------|--------|---------------|-------------------|
| 1 | 20/01/2025 | 09h-12h | Segunda-feira | Apresentação do curso, [Reprodutibilidade e estruturação de projeto](reprodutibilidade.qmd) |
| 1 | 22/01/2025 | 09h-12h |  Quarta-feira | [Produção de relatórios com Quarto](relatorios.qmd) |
| 2 | 29/01/2025 | 09h-12h |  Quarta-feira | [Produção de relatórios com Quarto (continuação)](relatorios.qmd) |
| 2 | 30/01/2025 | 09h-12h |  Quinta-feira (*) | [Produção de relatórios com Quarto (continuação)](relatorios.qmd) e [Introdução ao controle de versão com Git e GitHub](git-github.com) |
| 3 | 03/02/2025 | 09h-12h |  Segunda-feira | [Introdução ao controle de versão com Git e GitHub (continuação)](git-github.com)|
| 4 | 10/02/2025 | 09h-12h |  Segunda-feira | [Manipulação de textos e datas](texto-data.qmd) |
| 4 | 12/02/2025 | 09h-12h |  Quarta-feira | [Manipulação de textos e datas](texto-data.qmd) (continuação) e [Programação funcional e paralelização](programacao-funcional.qmd) |
| 5 | 17/02/2025 | 09h-12h |  Segunda-feira | [Programação funcional e paralelização (continuação)](programacao-funcional.qmd) |
| 5 | 19/02/2025 | 09h-12h |  Quarta-feira | [Dados espaciais](dados-espaciais.qmd) |   
| 6 | 24/02/2025 | 09h-12h  |  Segunda-feira | [Dados espaciais](dados-espaciais.qmd) (continuação) e [Introdução à *Big Data*](big-data.qmd) |
| 7 | 26/02/2025 | 09h-11h |  Quarta-feira | [Introdução à *Big Data*](big-data.qmd) (continuação) |

- (*): Atenção para as datas e horários diferentes.





